# Generated by Django 3.1.5 on 2021-01-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
