# Generated by Django 3.1.5 on 2021-01-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
        ('candidates', '0002_auto_20210130_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.job'),
        ),
    ]
